# Generated by Django 3.2.6 on 2021-08-14 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_portfoliouser_id'),
    ]

    operations = [
    ]
