# Generated by Django 3.2.6 on 2021-08-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_projects', '0002_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
