# Generated by Django 3.2.6 on 2021-08-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_projects', '0002_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
    ]
