# Generated by Django 3.2.6 on 2021-08-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_projects', '0003_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='.'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
