# Generated by Django 3.2.6 on 2021-08-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_projects', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pet',
            new_name='project',
        ),
    ]
